spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: ${spring.datasource.driver-class-name}
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.equipmentmanagementsystem.controller
    - group: 'admin'
      paths-to-match: '/**'
      packages-to-scan: com.equipmentmanagementsystem.controller.admin
    - group: 'user'
      paths-to-match: '/**'
      packages-to-scan: com.equipmentmanagementsystem.controller.user

knife4j:
  enable: true
  setting:
    language: zh_cn

alioss:
  endpoint: ${alioss.endpoint}
  access-key-id: ${alioss.access-key-id}
  access-key-secret: ${alioss.access-key-id}
  bucket-name: ${alioss.bucket-name}